version: 2
jobs:
  build:
    working_directory: ~/flux
    machine: true
    environment:
      GO_VERSION: 1.15.2
      # We don't need a GOPATH but CircleCI defines it, so we override it
      GOPATH: /home/circleci/go
      PATH: /bin:/usr/bin:/usr/local/go/bin:/home/circleci/go/bin
      # this image name must match what the Makefile builds
      BUILD_IMAGE: local/flux-adapter
      GA_IMAGE: docker.io/weaveworks/flux-adapter
      PRERELEASE_IMAGE: docker.io/weaveworks/flux-adapter-prerelease
    steps:
      - checkout
      - run:
          name: Install Golang
          command: |
            curl -OL https://storage.googleapis.com/golang/go${GO_VERSION}.linux-amd64.tar.gz
            tar -xf go${GO_VERSION}.linux-amd64.tar.gz
            sudo rm -rf /usr/local/go
            sudo mv go /usr/local
            mkdir -p "$HOME/go/bin"
            go version

      - run:
          name: Update packages
          command: |
            # These repos fail and we don't need them:
            sudo rm /etc/apt/sources.list.d/circleci_trusty.list /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update
            sudo apt-get install -y git rng-tools docker-ce
            git version
            docker version
      - restore_cache:
          keys:
            - go-build-{{ .Branch }}-{{ .Revision }}
            - go-build-{{ .Branch }}-
            - go-build-
      - restore_cache:
          keys:
            - go-modules-{{ checksum "go.mod" }}
            - go-modules-

#      - run: make test TEST_FLAGS="-race -tags integration -timeout 60s"
      # Give the image a name particular to this build
      - run: make image IMAGE_NAME="$BUILD_IMAGE:$CIRCLE_SHA1"
      - save_cache:
          key: go-build-{{ .Branch }}-{{ .Revision }}
          paths:
            - "~/.cache/go-build/"
      - save_cache:
          key: go-modules-{{ checksum "go.sum" }}
          paths:
            - "~/go/pkg/mod/"
      - deploy:
          name: Maybe push prerelease images
          command: |
            if [ -z "${CIRCLE_TAG}" -a "${CIRCLE_BRANCH}" == "master" ]; then
              TAG="${CIRCLE_BRANCH}-$(git rev-parse --short HEAD)"
              echo "$DOCKER_REGISTRY_PASSWORD" | docker login --username "$DOCKER_REGISTRY_USER" --password-stdin
              docker tag "$BUILD_IMAGE:$CIRCLE_SHA1" "$PRERELEASE_IMAGE:$TAG"
              docker push "$PRERELEASE_IMAGE:$TAG"
            fi
      - deploy:
          name: Maybe push release image
          command: |
            if echo "${CIRCLE_TAG}" | grep -Eq "^[0-9]+(\.[0-9]+)*(-[a-z]+)?$"; then
              TAG="${CIRCLE_TAG}"
              echo "$DOCKER_REGISTRY_PASSWORD" | docker login --username "$DOCKER_REGISTRY_USER" --password-stdin
              docker tag "$BUILD_IMAGE:$CIRCLE_SHA1" "$GA_IMAGE:$TAG"
              docker push "$GA_IMAGE:$TAG"
            fi

workflows:
  version: 2
  build-and-push:
    jobs:
      - build:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*(-[a-z]+)?/
